### ISSUE TITLE
Can not complete group tasks

### ISSUE THREAD

**Issue by psydex** [Citrinate/gleamSolver#10]
Some of the group tasks can be completed even if I join groups manually.
Stamstat.us shows Steam servers are fine so It could be the script?
![img](https://cloud.githubusercontent.com/assets/5594251/15450529/515508ee-1fa6-11e6-8655-69081cc6dc5e.png)

**Comment by Citrinate** [comment]
Steam Community may not be completely offline, but it's not 100% operational either.  Steamstat.us isn't giving the full picture.

There's something funky going on with Steam Community that prevents Gleam.io from seeing that you've joined a group.  Sometimes when this happens, it's impossible for you to join or leave a group.
