### ISSUE TITLE
Limit of the running gleam.solvers

### ISSUE THREAD

**Issue by silent332** [Citrinate/gleamSolver#11]
Hello! You can remove limit on the number of simultaneously running Gleam.solvers? I want to finish all the giveaways at the same time

**Comment by Citrinate** [comment]
This feature is for your own safety.  Gleam monitors how many entries you solve in a period of time.  If it's outside the limit of what a human is capable of, then you'll be banned.  Running the script on multiple pages at once could very easily exceed this limit.

**Comment by silent332** [comment]
you can upload an older version, where was this opportunity?

**Comment by Citrinate** [comment]
Old versions from before that feature will no longer work due to changes Gleam has made recently.

If you want to disable this feature, you'll need to open the editor in Greasemonkey/Tampermonkey and make the changes yourself.  You'll also need to disable automatic updates, or else re-do the change everytime I release a new version.

Look for the line:

`completeEntries: function() {`

Underneath that, look for and delete:
```
var in_progress = GM_getValue("script_in_progress", false);

if(in_progress !== false && +new Date() - in_progress <= entry_delay_max) {
	// Prevent the script from running on multiple pages at the same time
	gleamSolverUI.showNotification("in_progress", "Gleam.solver is currently running on another page.  Please wait.");
	gleamSolverUI.showUI();
} else {
	handleEntries();
}
```
And replace it with:
```
handleEntries();
```

**Comment by silent332** [comment]
thanks

**Comment by silent332** [comment]
Whether it is possible to speed up the script? for example to perform immediately after reloading the page and perform all the tasks at once, rather than one, maybe something else can be removed acceleration?

**Comment by Citrinate** [comment]
Changing the variables **_entry_delay_min_** and **_entry_delay_max_** both to 0 will allow the script to solve everything at once.  Early versions of the script did this and almost everyone was banned as a result.  It's probably possible to safely reduce these variables to something below their default values, but I don't know how far.

There's details [here](https://github.com/Citrinate/gleamSolver/issues/1#issuecomment-203227977) then on how to run the script automatically.

**Comment by silent332** [comment]
can you provide a link to your steam account or another means of communication? I need help with the script. I can as a thank you to send steam game cards

**Comment by Citrinate** [comment]
http://steamcommunity.com/id/Citrinate/
