### ISSUE TITLE
doesn't leave steam groups after

### ISSUE THREAD

**Issue by vioray** [Citrinate/gleamSolver#2]
noticed today that I was a member of dozens of steam groups that had been part of gleam entries but which gleam.solver hadn't retired from afterwards

**Comment by Citrinate** [comment]
Depending on what giveaways you were entering, this is intentional.  Specifically, this is what's supposed to happen if the script is running in "Raffle mode".

v1.3.5 makes it a whole lot clearer what mode the script is running in.
