### ISSUE TITLE
Check if profile is public ?

### ISSUE THREAD

**Issue by pizzahut2** [Citrinate/gleamSolver#4]
Can you add a check if the own Steam profile is public or not and stop solving in case it's not public? I normally always have my profile set to "friends only" and then it keeps trying to solve group joins.

I don't mind toggling the visibility of my profile myself, just am a bit scared that I may get a Gleam ban if I accidentally forget to make my profile public and the script isn't stopping then.

**Comment by Citrinate** [comment]
I tried to implement this, but just couldn't get it working.

There seems to be a delay between you switching your profile to public, and Gleam being able to see that you've switched your profile to public.  It's just not possible for me to predict what type of response Gleam will spit out.

Humans also have to deal with this issue, and the only way to deal with it is to keep clicking until Gleam stops giving an error.  This is exactly what the script appears to be doing, and so I don't think it's a cause for too much concern.

If you are still concerned, you can try to click on a Steam entry before running the script.  If you don't get a privacy error, then you're good to go.

**Comment by pizzahut2** [comment]
I was thinking that your script could go to
http://steamcommunity.com/my/edit/settings and read the status of this
(private / friends-only / public). But never mind, it's ok.

2016-04-12 14:36 GMT+02:00 Citrinate <notifications@github.com>:
