### ISSUE TITLE
bar clocking time left.

### ISSUE THREAD

**Issue by somokol** [Citrinate/gleamSolver#6]
When you have some free time, could you make it so the bar at top doesn't block the time left and entries info. Sometimes they post their contest right at the top of the page, and the black bar block the information. Pic shown...

http://imgur.com/QSPrPpM

Also, would it be possible to add in a script that converts the "time left" to an actual date the contest will end?

Thanks again for your fantastic work, and dedication in keeping it updated.

**Comment by Citrinate** [comment]
Added all of this in v1.4.12.  You can hover over those times now to see the exact end date in your timezone.

**Comment by somokol** [comment]
HOT DAMN YOU'RE BRILLIANT!!!!!! THANK YOU!
