### ISSUE TITLE
Suggestion?

### ISSUE THREAD

**Issue by kirby193** [Citrinate/gleamSolver#9]
Would it be possible to add accounts for certain social medias inside of the script, like a major one for every group that users could use?  I'm not too sure how it would work, but maybe encrypt account details in it or something of the sort?

Like an account for twitter, instagram, telegram, etc.

Yea, I could just make a new account for each service, but this could be used for everybody.

Just a thought

**Comment by Citrinate** [comment]
If I understand you correctly, you're asking if there could be a single account dedicated to all people using this script.  The answer to that would be no.  Gleam only allows a social media account to be linked to a single Gleam account.
